#!/usr/bin/env python3
"""
Build script to package TV Viewer as a single executable.
Supports both Windows and Linux.

Usage:
    python build.py          # Build for current platform
    python build.py --onefile # Single file executable
    python build.py --clean   # Clean build artifacts
"""

import os
import sys
import shutil
import subprocess
import platform

# Build configuration
APP_NAME = "TV_Viewer"
MAIN_SCRIPT = "main.py"
ICON_FILE = "tv_viewer.ico"

# Files and folders to include
DATA_FILES = [
    ("config.py", "."),
    ("channels.json", ".") if os.path.exists("channels.json") else None,
]
DATA_FILES = [f for f in DATA_FILES if f is not None]

# Hidden imports that PyInstaller might miss.
# NOTE: pychromecast / zeroconf were previously listed here. They were dropped
# because (a) they are guarded by try/except in ui/player_window.py so the app
# runs fine without them, and (b) zeroconf's mDNS discovery code is a known
# Windows Defender false-positive trigger. Cast support is restored by the
# user installing pychromecast separately or by an opt-in installer variant.
HIDDEN_IMPORTS = [
    "vlc",
    "aiohttp",
    "asyncio",
    "tkinter",
    "tkinter.ttk",
    "customtkinter",
    "customtkinter.windows",
    "customtkinter.windows.widgets",
    "tkintermapview",
    "tkintermapview.canvas_position_marker",
    "json",
    "threading",
    "queue",
    "PIL",
    "PIL.Image",
    "PIL.ImageTk",
    "PIL._tkinter_finder",
    "PIL._imagingtk",
]

# Excluded modules. The PIL.* and chromecast/zeroconf entries below directly
# reduce Defender false-positive surface and shave ~12 MB from the bundle.
EXCLUDED_MODULES = [
    # Heavy data-science libs that may transitively get pulled in
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "cv2",
    "tensorflow",
    "torch",
    "sklearn",
    # Cast / mDNS — AV-flagged + optional feature
    "pychromecast",
    "casttube",
    "zeroconf",
    "google.protobuf",
    "google",
    # Pillow plugins that the app never touches (saves ~8 MB and removes
    # a frequently AV-flagged native binary, _avif.pyd)
    "PIL._avif",
    "PIL._webp",
    "PIL._imagingcms",
    "PIL.ImageCms",
    "PIL.AvifImagePlugin",
    "PIL.WebPImagePlugin",
    # Stdlib test scaffolding never needed at runtime
    "test",
    "tests",
    "unittest",
    "pydoc_data",
    "distutils.tests",
    "lib2to3",
    "idlelib",
    "turtle",
    "turtledemo",
]


def write_version_file(path: str) -> None:
    """Write a Windows VERSIONINFO resource so the EXE has proper metadata.

    Defender's SmartScreen / cloud-reputation checks weight signed metadata
    and version resources heavily — adding these reduces the chance of a
    fresh build being flagged as unknown / suspicious.
    """
    try:
        import config as _cfg
        version = getattr(_cfg, "APP_VERSION", "1.0.0")
    except Exception:
        version = "1.0.0"

    parts = [int(x) for x in (version.split(".") + ["0", "0", "0", "0"])[:4]]
    ver_tuple = f"({parts[0]}, {parts[1]}, {parts[2]}, {parts[3]})"

    content = f"""# Auto-generated by build.py — do not edit
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={ver_tuple},
    prodvers={ver_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'TV Viewer Project'),
         StringStruct(u'FileDescription', u'TV Viewer — IPTV streaming application'),
         StringStruct(u'FileVersion', u'{version}'),
         StringStruct(u'InternalName', u'{APP_NAME}'),
         StringStruct(u'LegalCopyright', u'Open source — MIT License'),
         StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
         StringStruct(u'ProductName', u'TV Viewer'),
         StringStruct(u'ProductVersion', u'{version}')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def check_pyinstaller():
    """Check if PyInstaller is installed."""
    try:
        import PyInstaller
        return True
    except ImportError:
        print("PyInstaller not found. Installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])
        return True


def create_icon():
    """Create the icon file if it doesn't exist."""
    if not os.path.exists(ICON_FILE):
        try:
            from icon import get_icon_path
            icon_path = get_icon_path()
            if icon_path and os.path.exists(icon_path):
                if icon_path != ICON_FILE:
                    shutil.copy(icon_path, ICON_FILE)
                print(f"Icon created: {ICON_FILE}")
        except Exception as e:
            print(f"Could not create icon: {e}")


def clean_build():
    """Clean previous build artifacts."""
    dirs_to_remove = ["build", "dist", "__pycache__"]
    files_to_remove = [f"{APP_NAME}.spec"]
    
    for d in dirs_to_remove:
        if os.path.exists(d):
            shutil.rmtree(d)
            print(f"Removed: {d}")
    
    for f in files_to_remove:
        if os.path.exists(f):
            os.remove(f)
            print(f"Removed: {f}")
    
    # Clean __pycache__ in subdirectories
    for root, dirs, files in os.walk("."):
        for d in dirs:
            if d == "__pycache__":
                path = os.path.join(root, d)
                shutil.rmtree(path)
                print(f"Removed: {path}")


def build_executable(onefile=True):
    """Build the executable using PyInstaller."""
    check_pyinstaller()
    create_icon()
    
    # Base PyInstaller command
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", APP_NAME,
        "--clean",
        "--noconfirm",
        # Explicitly disable UPX — UPX-compressed binaries are heavily
        # flagged by Windows Defender as suspicious. PyInstaller 6+ defaults
        # to no UPX but pin it for clarity.
        "--noupx",
    ]

    # Windows-only: embed VERSIONINFO so Defender SmartScreen treats the
    # binary as a properly-published file rather than an "unknown".
    if platform.system() == "Windows":
        version_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "version_info.txt")
        write_version_file(version_file)
        cmd.extend(["--version-file", version_file])
    
    # Single file or directory
    if onefile:
        cmd.append("--onefile")
    else:
        cmd.append("--onedir")
    
    # Windowed mode (no console) - comment out for debugging
    if platform.system() == "Windows":
        cmd.append("--windowed")
    
    # Icon
    if os.path.exists(ICON_FILE):
        cmd.extend(["--icon", ICON_FILE])
    
    # Hidden imports
    for imp in HIDDEN_IMPORTS:
        cmd.extend(["--hidden-import", imp])
    
    # Excluded modules
    for exc in EXCLUDED_MODULES:
        cmd.extend(["--exclude-module", exc])
    
    # Data files
    for src, dst in DATA_FILES:
        if os.path.exists(src):
            sep = ";" if platform.system() == "Windows" else ":"
            cmd.extend(["--add-data", f"{src}{sep}{dst}"])

    # Optional libvlc bundling (#200) — when CI sets BUNDLE_LIBVLC_DIR,
    # we ship libvlc.dll/libvlccore.dll + plugins/ inside the EXE so the
    # app runs on a clean Windows install with no VLC prerequisite.
    libvlc_dir = os.environ.get("BUNDLE_LIBVLC_DIR", "").strip()
    if libvlc_dir and os.path.isdir(libvlc_dir):
        sep = ";" if platform.system() == "Windows" else ":"
        for fname in ("libvlc.dll", "libvlccore.dll"):
            fpath = os.path.join(libvlc_dir, fname)
            if os.path.isfile(fpath):
                cmd.extend(["--add-binary", f"{fpath}{sep}."])
        plugins_dir = os.path.join(libvlc_dir, "plugins")
        if os.path.isdir(plugins_dir):
            cmd.extend(["--add-data", f"{plugins_dir}{sep}plugins"])
        print(f"Bundling libvlc from: {libvlc_dir}")

    # Add the main script
    cmd.append(MAIN_SCRIPT)
    
    print("Building with command:")
    print(" ".join(cmd))
    print()
    
    # Run PyInstaller
    result = subprocess.run(cmd)
    
    if result.returncode == 0:
        print("\n" + "=" * 50)
        print("BUILD SUCCESSFUL!")
        print("=" * 50)
        
        if onefile:
            if platform.system() == "Windows":
                exe_path = os.path.join("dist", f"{APP_NAME}.exe")
            else:
                exe_path = os.path.join("dist", APP_NAME)
            print(f"\nExecutable: {os.path.abspath(exe_path)}")
        else:
            dist_path = os.path.join("dist", APP_NAME)
            print(f"\nApplication folder: {os.path.abspath(dist_path)}")
        
        print("\nNOTE: VLC must be installed on the target system!")
        print("      Windows: https://www.videolan.org/vlc/")
        print("      Linux: sudo apt install vlc")
    else:
        print("\nBuild failed!")
        return False
    
    return True


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Build TV Viewer executable")
    parser.add_argument("--clean", action="store_true", help="Clean build artifacts")
    parser.add_argument("--onefile", action="store_true", help="Build single file (may be blocked by corporate security policies)")
    parser.add_argument("--onedir", action="store_true", default=True, help="Build directory (default, works everywhere)")
    parser.add_argument("--debug", action="store_true", help="Build with console for debugging")
    
    args = parser.parse_args()
    
    # Change to script directory
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    if args.clean:
        clean_build()
        return
    
    onefile = args.onefile  # Default is onedir unless --onefile explicitly passed
    build_executable(onefile=onefile)


if __name__ == "__main__":
    main()
