#!/usr/bin/env python3
"""TV Viewer — Supabase Interactive Setup Script.

This script helps you configure the Supabase connection for TV Viewer analytics.
It will:
  1. Prompt for your Supabase project URL and anon key
  2. Validate connectivity by inserting and reading a test event
  3. Save credentials to a .env file (gitignored)
  4. Print instructions for GitHub Secrets (CI builds)

PRIVACY NOTICE:
  No personal data is collected. All device IDs and channel URLs are SHA-256
  hashed before being sent to Supabase. The anon key only allows INSERT to
  analytics_events (write-only) and read/write to channel_status.

Usage:
    python scripts/supabase_setup.py
    python scripts/supabase_setup.py --url https://xxx.supabase.co --key eyJ...
    python scripts/supabase_setup.py --test-only    # Test existing .env config
    python scripts/supabase_setup.py --verify-schema # Check if tables exist

Requires: pip install requests
"""

import os
import sys
import json
import uuid
import hashlib
import argparse
import re
from pathlib import Path
from datetime import datetime

try:
    import requests
except ImportError:
    print("ERROR: 'requests' package is required.")
    print("  Install it with: pip install requests")
    sys.exit(1)

try:
    import base64 as _b64
except ImportError:
    _b64 = None

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"
REQUIRED_TABLES = ["analytics_events", "channel_status"]

# ANSI color helpers (disabled on Windows cmd without VT support)
_COLOR = os.environ.get("TERM") or os.name != "nt"


def _c(code: str, text: str) -> str:
    """Apply ANSI color if terminal supports it."""
    if _COLOR:
        return f"\033[{code}m{text}\033[0m"
    return text


def green(t): return _c("32", t)
def red(t): return _c("31", t)
def yellow(t): return _c("33", t)
def cyan(t): return _c("36", t)
def bold(t): return _c("1", t)


# ---------------------------------------------------------------------------
# .env file handling
# ---------------------------------------------------------------------------
def load_env_file(path: Path) -> dict:
    """Parse a .env file into a dict. Handles quotes and comments."""
    env = {}
    if not path.exists():
        return env
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            # Strip surrounding quotes
            if (value.startswith('"') and value.endswith('"')) or \
               (value.startswith("'") and value.endswith("'")):
                value = value[1:-1]
            env[key] = value
    return env


def save_env_file(path: Path, env: dict):
    """Write env dict to a .env file with header comment."""
    lines = [
        "# TV Viewer — Supabase Configuration",
        "# Generated by scripts/supabase_setup.py",
        f"# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "#",
        "# WARNING: This file contains API keys. It is gitignored.",
        "# Do NOT commit this file to version control.",
        "#",
        "# For CI builds, add these as GitHub Secrets:",
        "#   SUPABASE_URL, SUPABASE_ANON_KEY",
        "",
    ]
    for key, value in env.items():
        lines.append(f"{key}={value}")
    lines.append("")  # trailing newline

    path.write_text("\n".join(lines), encoding="utf-8")


def apply_env_to_os(env: dict):
    """Set env vars in the current process (for subsequent operations)."""
    for key, value in env.items():
        os.environ[key] = value


# ---------------------------------------------------------------------------
# Supabase API helpers
# ---------------------------------------------------------------------------
def _headers(key: str) -> dict:
    return {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    }


def test_connectivity(url: str, key: str) -> tuple[bool, str]:
    """Basic connectivity test — hit the REST API root."""
    try:
        resp = requests.get(
            f"{url}/rest/v1/",
            headers=_headers(key),
            timeout=10,
        )
        if resp.status_code == 200:
            return True, "Connected to Supabase REST API"
        return False, f"Unexpected status: {resp.status_code} — {resp.text[:200]}"
    except requests.exceptions.ConnectionError:
        return False, "Connection failed. Check SUPABASE_URL."
    except requests.exceptions.Timeout:
        return False, "Connection timed out."
    except Exception as e:
        return False, f"Error: {e}"


def verify_table_exists(url: str, key: str, table: str) -> tuple[bool, str]:
    """Check if a table exists by querying it with limit=0."""
    try:
        resp = requests.get(
            f"{url}/rest/v1/{table}?select=id&limit=0",
            headers=_headers(key),
            timeout=10,
        )
        if resp.status_code == 200:
            return True, f"Table '{table}' exists"
        elif resp.status_code == 404:
            return False, f"Table '{table}' not found — run supabase_setup.sql first"
        else:
            return False, f"Table '{table}': HTTP {resp.status_code} — {resp.text[:100]}"
    except Exception as e:
        return False, f"Error checking '{table}': {e}"


def insert_test_event(url: str, key: str) -> tuple[bool, str, str | None]:
    """Insert a test analytics event and return its ID."""
    test_device_id = hashlib.sha256(
        f"setup-test-{uuid.uuid4()}".encode()
    ).hexdigest()

    payload = {
        "device_id": test_device_id,
        "event_type": "app_open",
        "event_data": {
            "source": "supabase_setup.py",
            "test": True,
            "timestamp": datetime.utcnow().isoformat(),
        },
        "app_version": "setup-test",
        "platform": "setup",
    }

    try:
        resp = requests.post(
            f"{url}/rest/v1/analytics_events",
            headers=_headers(key),
            json=payload,
            timeout=10,
        )
        if resp.status_code in (200, 201):
            data = resp.json()
            if data and isinstance(data, list) and len(data) > 0:
                event_id = data[0].get("id", "unknown")
                return True, f"Test event inserted (id: {event_id[:8]}...)", event_id
            return True, "Test event inserted (no ID returned)", None
        else:
            return False, f"Insert failed: HTTP {resp.status_code} — {resp.text[:200]}", None
    except Exception as e:
        return False, f"Insert error: {e}", None


def verify_rls_write_only(url: str, key: str) -> tuple[bool, str]:
    """Verify that anon key CANNOT read analytics_events (RLS enforcement)."""
    try:
        resp = requests.get(
            f"{url}/rest/v1/analytics_events?select=id&limit=1",
            headers=_headers(key),
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            if isinstance(data, list) and len(data) == 0:
                return True, "RLS verified: anon cannot read analytics_events (empty result)"
            else:
                return False, (
                    "WARNING: anon key CAN read analytics_events! "
                    "RLS may not be configured correctly. "
                    "Run the full supabase_setup.sql to enable RLS policies."
                )
        # A 403 or other error also means RLS is blocking reads (good)
        return True, f"RLS verified: read blocked (HTTP {resp.status_code})"
    except Exception as e:
        return False, f"RLS check error: {e}"


def test_channel_status_readwrite(url: str, key: str) -> tuple[bool, str]:
    """Verify channel_status allows INSERT and SELECT for anon."""
    test_hash = hashlib.sha256(
        f"test-channel-{uuid.uuid4()}".encode()
    ).hexdigest()
    test_device = hashlib.sha256(
        f"test-device-{uuid.uuid4()}".encode()
    ).hexdigest()

    payload = {
        "channel_url_hash": test_hash,
        "is_working": True,
        "checked_by": test_device,
        "app_version": "setup-test",
        "response_time_ms": 123,
    }

    try:
        # Test INSERT
        resp = requests.post(
            f"{url}/rest/v1/channel_status",
            headers=_headers(key),
            json=payload,
            timeout=10,
        )
        if resp.status_code not in (200, 201):
            return False, f"channel_status INSERT failed: HTTP {resp.status_code}"

        # Test SELECT
        resp = requests.get(
            f"{url}/rest/v1/channel_status?channel_url_hash=eq.{test_hash}&limit=1",
            headers=_headers(key),
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            if isinstance(data, list) and len(data) > 0:
                return True, "channel_status read/write verified"
            return False, "channel_status SELECT returned empty (RLS may block reads)"
        return False, f"channel_status SELECT failed: HTTP {resp.status_code}"
    except Exception as e:
        return False, f"channel_status test error: {e}"


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------
def validate_url(url: str) -> tuple[bool, str]:
    """Validate Supabase URL format."""
    url = url.strip().rstrip("/")
    if not url:
        return False, "URL cannot be empty"
    if not url.startswith("https://"):
        return False, "URL must start with https://"
    # Supabase URLs: https://<project-ref>.supabase.co
    pattern = r"^https://[a-z0-9-]+\.supabase\.co$"
    if not re.match(pattern, url):
        return False, (
            "URL should match pattern: https://<project-ref>.supabase.co\n"
            f"  Got: {url}"
        )
    return True, url


def validate_key(key: str) -> tuple[bool, str]:
    """Validate Supabase anon key format (JWT) and ensure it's not the service_role key."""
    key = key.strip()
    if not key:
        return False, "Key cannot be empty"
    if not key.startswith("eyJ"):
        return False, "Anon key should be a JWT starting with 'eyJ'"
    if len(key) < 100:
        return False, "Anon key seems too short for a Supabase JWT"
    # Decode JWT payload to verify it's the anon key, not service_role
    if _b64:
        try:
            payload_b64 = key.split(".")[1]
            # Add padding if needed
            payload_b64 += "=" * (4 - len(payload_b64) % 4)
            payload = json.loads(_b64.urlsafe_b64decode(payload_b64))
            role = payload.get("role", "")
            if role == "service_role":
                return False, (
                    "This is the SERVICE_ROLE key (admin privileges). "
                    "Use the ANON key instead.\n"
                    "  → Supabase Dashboard > Project Settings > API > anon (public)"
                )
        except Exception:
            pass  # Can't decode — skip role check, proceed with other validation
    return True, key


# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------
def prompt_credentials() -> tuple[str, str]:
    """Interactively prompt for Supabase URL and anon key."""
    print()
    print(bold("=" * 60))
    print(bold("  TV Viewer — Supabase Setup"))
    print(bold("=" * 60))
    print()
    print("  You'll need your Supabase project credentials:")
    print("  → Supabase Dashboard > Project Settings > API")
    print()
    print("  " + yellow("IMPORTANT: Make sure you've already run supabase_setup.sql"))
    print("  " + yellow("in the Supabase SQL Editor to create the tables!"))
    print()

    # Prompt for URL
    while True:
        url = input(cyan("  Supabase Project URL: ")).strip()
        valid, result = validate_url(url)
        if valid:
            url = result
            break
        print(f"  {red('✗')} {result}")

    # Prompt for anon key
    while True:
        key = input(cyan("  Supabase Anon Key: ")).strip()
        valid, result = validate_key(key)
        if valid:
            key = result
            break
        print(f"  {red('✗')} {result}")

    return url, key


# ---------------------------------------------------------------------------
# Main setup flow
# ---------------------------------------------------------------------------
def run_tests(url: str, key: str) -> bool:
    """Run all connectivity and schema tests. Returns True if all pass."""
    print()
    print(bold("  Running connectivity tests..."))
    print()

    all_passed = True

    # Test 1: Basic connectivity
    ok, msg = test_connectivity(url, key)
    status = green("✓") if ok else red("✗")
    print(f"  {status} {msg}")
    if not ok:
        return False

    # Test 2: Verify tables exist
    for table in REQUIRED_TABLES:
        ok, msg = verify_table_exists(url, key, table)
        status = green("✓") if ok else red("✗")
        print(f"  {status} {msg}")
        if not ok:
            all_passed = False

    if not all_passed:
        print()
        print(red("  Some tables are missing. Please run supabase_setup.sql first:"))
        print("  → Supabase Dashboard > SQL Editor > New Query > paste & run")
        return False

    # Test 3: Insert a test event
    ok, msg, event_id = insert_test_event(url, key)
    status = green("✓") if ok else red("✗")
    print(f"  {status} {msg}")
    if not ok:
        all_passed = False

    # Test 4: Verify RLS (anon cannot read analytics)
    ok, msg = verify_rls_write_only(url, key)
    status = green("✓") if ok else yellow("⚠")
    print(f"  {status} {msg}")
    if not ok:
        # This is a warning, not a failure — still functional
        print(f"    {yellow('RLS not enforced. Analytics data may be readable by clients.')}")

    # Test 5: channel_status read/write
    ok, msg = test_channel_status_readwrite(url, key)
    status = green("✓") if ok else red("✗")
    print(f"  {status} {msg}")
    if not ok:
        all_passed = False

    return all_passed


def print_github_secrets_instructions(url: str, key: str):
    """Print instructions for adding secrets to GitHub."""
    print()
    print(bold("=" * 60))
    print(bold("  GitHub Secrets Setup (for CI builds)"))
    print(bold("=" * 60))
    print()
    print("  Add these secrets to your GitHub repository:")
    print("  → Repository > Settings > Secrets and variables > Actions")
    print()
    print(f"  Secret Name:  {cyan('SUPABASE_URL')}")
    print(f"  Secret Value: {url}")
    print()
    print(f"  Secret Name:  {cyan('SUPABASE_ANON_KEY')}")
    print(f"  Secret Value: {key[:20]}...{key[-10:]}")
    print(f"  (full key saved in .env file)")
    print()
    print("  The android-build.yml workflow will automatically pass these")
    print("  as --dart-define arguments during flutter build.")
    print()


def print_local_dev_instructions():
    """Print instructions for local development."""
    print()
    print(bold("  Local Development"))
    print(bold("  " + "-" * 40))
    print()
    print("  For Flutter development, pass the env vars at build time:")
    print()
    print(cyan("    # Read from .env and build"))
    print(cyan('    flutter run --dart-define=SUPABASE_URL=<url> \\'))
    print(cyan('                --dart-define=SUPABASE_ANON_KEY=<key>'))
    print()
    print("  For Python scripts (dashboard, etc.):")
    print()
    print(cyan("    # PowerShell"))
    print(cyan("    $env:SUPABASE_URL = '<url>'"))
    print(cyan("    $env:SUPABASE_ANON_KEY = '<key>'"))
    print(cyan("    python scripts/analytics_dashboard.py"))
    print()
    print(cyan("    # Or just run — the dashboard auto-loads from .env"))
    print(cyan("    python scripts/analytics_dashboard.py"))
    print()


def main():
    parser = argparse.ArgumentParser(
        description="TV Viewer — Supabase Setup",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/supabase_setup.py                    # Interactive setup\n"
            "  python scripts/supabase_setup.py --test-only        # Test existing .env\n"
            "  python scripts/supabase_setup.py --verify-schema    # Check tables exist\n"
            "  python scripts/supabase_setup.py --url URL --key KEY  # Non-interactive\n"
        ),
    )
    parser.add_argument("--url", help="Supabase project URL")
    parser.add_argument("--key", help="Supabase anon key")
    parser.add_argument(
        "--test-only",
        action="store_true",
        help="Only test connectivity (load from .env)",
    )
    parser.add_argument(
        "--verify-schema",
        action="store_true",
        help="Verify that required tables exist",
    )
    args = parser.parse_args()

    # Determine credentials source
    url = args.url or os.environ.get("SUPABASE_URL", "")
    key = args.key or os.environ.get("SUPABASE_ANON_KEY", "")

    # Try loading from .env if not provided
    if not url or not key:
        env = load_env_file(ENV_FILE)
        url = url or env.get("SUPABASE_URL", "")
        key = key or env.get("SUPABASE_ANON_KEY", "")

    # Test-only mode: just run tests with existing credentials
    if args.test_only:
        if not url or not key:
            print(red("  ERROR: No credentials found."))
            print("  Run 'python scripts/supabase_setup.py' to configure,")
            print("  or set SUPABASE_URL and SUPABASE_ANON_KEY env vars.")
            sys.exit(1)
        success = run_tests(url, key)
        sys.exit(0 if success else 1)

    # Schema verification only
    if args.verify_schema:
        if not url or not key:
            print(red("  ERROR: No credentials found."))
            sys.exit(1)
        print(bold("\n  Verifying schema..."))
        all_ok = True
        for table in REQUIRED_TABLES:
            ok, msg = verify_table_exists(url, key, table)
            status = green("✓") if ok else red("✗")
            print(f"  {status} {msg}")
            if not ok:
                all_ok = False
        sys.exit(0 if all_ok else 1)

    # Interactive setup
    if not url or not key:
        url, key = prompt_credentials()
    else:
        # Validate provided credentials
        ok, result = validate_url(url)
        if not ok:
            print(red(f"  Invalid URL: {result}"))
            sys.exit(1)
        url = result

        ok, result = validate_key(key)
        if not ok:
            print(red(f"  Invalid key: {result}"))
            sys.exit(1)
        key = result

    # Run connectivity tests
    success = run_tests(url, key)

    if not success:
        print()
        print(red("  Setup failed. Please fix the issues above and try again."))
        print()
        print("  Common fixes:")
        print("  1. Run supabase_setup.sql in the Supabase SQL Editor")
        print("  2. Check that the URL and anon key are correct")
        print("  3. Ensure your Supabase project is active (not paused)")
        sys.exit(1)

    # Save to .env file
    print()
    print(bold("  Saving credentials..."))

    env_data = load_env_file(ENV_FILE)  # Preserve any existing entries
    env_data["SUPABASE_URL"] = url
    env_data["SUPABASE_ANON_KEY"] = key
    save_env_file(ENV_FILE, env_data)
    apply_env_to_os(env_data)

    print(f"  {green('✓')} Saved to {ENV_FILE}")
    print(f"  {green('✓')} .env is gitignored (will not be committed)")

    # Print next steps
    print_github_secrets_instructions(url, key)
    print_local_dev_instructions()

    print(bold("=" * 60))
    print(green(bold("  ✓ Supabase setup complete!")))
    print(bold("=" * 60))
    print()


if __name__ == "__main__":
    main()
